# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNExactTarget' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'JB4ASDK', '~> 4.7.0'

  # Pods for RNExactTarget

end
